### ISSUE TITLE
Cannot open jar file in gnu/linux (mint)

### ISSUE THREAD

**Issue by ADepic** [Nasso/urmusic-desktop#10]
When I run ` java -jar urmusic-desktop-alpha-0.4.0.jar `, I get this:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/application/Application
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1009)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:545)
	at java.base/java.net.URLClassLoader.access$100(URLClassLoader.java:83)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:453)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:447)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:446)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:374)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 14 more

```

**Comment by nasso** [comment]
This versino of urmusic requires JavaFX, which I think isn't necessarily included with OpenJDK?
You have to get it somehow, but I have never did that myself, so if you manage to get it to work, please share!

**Comment by ADepic** [comment]
Might I mention, only ffmpeg.exe is included and not ffmpeg Linux binary.

Also I made an issue for urmusic5, for me its seems to not be able to load music files.

For urmusic 5, where are all the presets anyway ?

**Comment by nasso** [comment]
Yeah I only provided the ffmpeg Windows binaries in this version.
I haven't made presets for urmusic5 yet, and as it uses a completely different, binary format for project files, older ones aren't compatible.
